### ISSUE TITLE
Check `keyboardVerticalOffset` for iPhones > version 12

### ISSUE THREAD

**Issue by donni106** [smart-village-solutions/smart-village-app-app#260]
https://github.com/ikuseiGmbH/smart-village-app-app/blob/5928d7848becd5e440a0b92ddeada26a04f76871/src/screens/FormScreen.js#L69-L76

https://github.com/ikuseiGmbH/smart-village-app-app/blob/5928d7848becd5e440a0b92ddeada26a04f76871/src/screens/BB-BUS/IndexScreen.js#L152-L159

Newer iPhones can have different header sizes, which we do not consider in calculation. This needs to be approved.

**Comment by donni106** [comment]
@d4v3d4vE do you think there still can be issues with iPhones and our Keyboard implementations?

**Comment by d4v3d4vE** [comment]
should't be an issue for my understanding, also just tested it on the newest devices and it looks good.
