### ISSUE TITLE
Implement better user interface/layout for dates in time ranges?

### ISSUE THREAD

**Issue by donni106** [smart-village-solutions/smart-village-app-app#31]
Issue results from: https://github.com/ikuseiGmbH/smart-village-app-mainserver/issues/92

Should we implement a better user interface/layout for dates in time ranges?
A bit more like on the website: https://www.reiseland-brandenburg.de/poi/flaeming/angelgewaesser/angelteiche-werdermuehle?

> * frontend group by `dateFrom`/`dateEnd`
>   * but only for `weekday` = `monday` - `sunday_holiday`
> * separate time blocks for every group (swipe like on web page?)
> * other data listed beneath

**Comment by SoleCincis** [comment]
I would be happy to work on this feature if requested
