### ISSUE TITLE
turning off location services in settings feels kind of laggy

### ISSUE THREAD

**Issue by donni106** [smart-village-solutions/smart-village-app-app#391]
when toggling settings like push and matomo it always feels smooth. when turning on location services it feels the same. but when turning off the location services there is a lag and the loading indicator is missing as well.
sadly i was not able to find a reason or to fix that behavior.

**Comment by donni106** [comment]
@ardasnturk do we still have this problem?

**Comment by donni106** [comment]
@d4v3d4vE do we still have this problem?

**Comment by ardasnturk** [comment]
I have not encountered such a problem, please test it and let us know. ☺️ @d4v3d4vE

**Comment by d4v3d4vE** [comment]
I've also not encountered this problem, works smooth. 😄
